# Generated by Django 3.1.3 on 2020-11-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.CreateModel(
            name='CurrentStatusOfTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.IntegerField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ManyToManyField(through='board.CurrentStatusOfTask', to='board.Status'),
        ),
    ]
